.travis.yml, docker-compose.yml, mongoid.yml
Configures travis & adds mongo_test container separate from mongo_dev so that dev work doesn't stomp on test work.
=> run travis tests via docker

bin/add_ht_items.rb
* Add `ocn_resolution` model to requires
* Skip HT items that don't have any OCNs to avoid
error "E11000 duplicate key error collection: test.clusters index: ocns_1 dup key: { ocns: undefined } (11000) (on mongo:27017, legacy retry, attempt 1) (on mongo:27017, legacy retry, attempt 1) (Mongo::Error::OperationFailure)"
=> Let bin/add_ht_items.rb run at all

Gemfile, bin/add_ht_items.rb, bin/add_ocn_resolutions.rb, bin/add_print_holdings.rb, lib/cluster_ht_item.rb, lib/ht_item.rb, lib/reclusterer.rb, lib/utils/waypoint.rb, spec/cluster_ht_item_spec.rb, spec/cluster_ocn_resolution_spec.rb, spec/cluster_serial_spec.rb
Uses reclusterer. Delete is similar to OCNResolution delete, but searches for item_id instead of OCN. ClusterHTItem.update deletes then clusters updated record.
=> HT-2376 update / delete

bin/add_ht_items.rb, lib/cluster.rb, lib/cluster_ht_item.rb, lib/ht_item.rb, spec/cluster_holding_spec.rb, spec/cluster_ht_item_spec.rb, spec/ht_item_spec.rb
HT Items without OCNs now create a bare bones Cluster when added. They will not cluster with anything else. Updates to HT Items are keyed on item_id. 
This required changes to the Cluster.ocns index, HTItem.ocns validation, and a minor change to HTItem clustering.
=> HT-2383 create clusters for HTItems w/o OCNs

bin/add_ht_items.rb, lib/enum_chron_parser.rb, lib/ht_item.rb, spec/ht_item_spec.rb
Added n_enum and n_chron to ht_items. They are populated by the enumchronparser (such as it is) when an ht_item is created with a enum_chron value.
Based on the changes in the autoscrub branch (where the enumchronparser first got added) which hasn't been merged to master yet.
=> Ht 2428 (n_enum & n_chron for mpms)

bin/add_print_holdings.rb, lib/cluster_holding.rb, lib/holding.rb, spec/cluster_holding_spec.rb, spec/factories/holding.rb, spec/holding_spec.rb
Adds the option to update holdings with bin/add_print_holdings.rb
ClusterHolding.new(h).update finds a matching holdings record and updates its received_date, or adds it if none can be found. For our purposes matching means all fields are identical except date_received. This overrides Holding's == method. 
After updating holdings records, bin/add_print_holdings.rb deletes any remaining holdings from the particular organization and an older date_received. 
While testing it was discovered the Cluster.ocns index was not being used resulting in full column scans. The partial filter has been changed from "ocns.0" : {$exists:1} to ocns :{$gt:1}
=> Update holdings records, delete old holdings

lib/cluster.rb
One line change to the ocns index for clusters. "ocns.0" prevents usage for general ocn queries. Ocns $gt > 0 ensures non-existent OCNs aren't indexed and the resulting duplicate key error, while still being used for queries. 
This was claimed in PR 28 (HT-2378), but was omitted accidentally during some ham-fisted git operations. It didn't have any particular relationship to said ticket anyway.
=> Fix Cluster ocns index to prevent collscans

bin/add_ht_items.rb, bin/export_overlap_report.rb, lib/cluster_overlap.rb, lib/holding.rb, lib/ht_item.rb, lib/multi_part_overlap.rb, lib/overlap.rb, lib/serial_overlap.rb, lib/single_part_overlap.rb, spec/cluster_overlap_spec.rb, spec/factories/holding.rb, spec/holding_spec.rb, spec/multi_part_overlap_spec.rb, spec/overlap_report_spec.rb, spec/overlap_spec.rb, spec/serial_overlap_spec.rb, spec/single_part_overlap_spec.rb
Adds `condition` to Holdings records.
Adds `content_provider_code` to HTItems
Adds Overlap record class to compute holdings *_counts for a Serial cluster (does almost nothing since we don't really need it)
Adds SinglePartOverlap for SPMs.
Adds MultiPartOverlap for MPMs.
Adds CollectOverlap to iterate over overlapping HTItems.
Adds `bin/export_overlap_report.rb umich` to dump the results from CollectOverlap as tsv
Known issues:
It raises an error when dealing with "ser/spm" clusters. What are we supposed to do with them?
access_count is wrong. I am only seeing documentation for UMich's brittle access program. Is this relevant for ETAS and is it computed differently.
MPMs are likely computed incorrectly or at least differently from existing practice.
Handling of MPMs without enum_chrons is …
=> First attempt at generating holdings overlap reports

docker-compose.yml, lib/holding.rb, lib/ht_members.rb, lib/services.rb, spec/cost_report_spec.rb, spec/holding_spec.rb, spec/holdings_db_spec.rb, spec/ht_members_spec.rb
- Uses canister for holdings DB & global cache of member info
- Auto-sets organization & country code when constructing holding
Supercedes #37
=> HT-2454: HTMember with country code & weight

lib/enum_chron.rb, lib/holding.rb, lib/ht_item.rb, spec/holding_spec.rb
First commit duplicates the HTItem enumchron normalization code/tests for Holdings. 
Second commit moves duplicative code into a module. Maybe silly.
=> Ht 2467 holdings enumchron

spec/ht_item_overlap_spec.rb
A single test to confirm the allocation of hshares for KEIO contributed items. It is redundant, but makes the relationship of hshares and HTItem billing entities more explicit. Also, HT-2623.
=> Test for KEIO contributed items

spec/fixtures/collections.rb, spec/ht_collections_spec.rb, spec/ht_item_overlap_spec.rb, spec/single_part_overlap_spec.rb
This is expected behavior, although it may not be current behavior. This has the potential to create a few dollar discrepancy that will need explaining later.
* OKS was removed from the HTCollections fixture because rubocop was complaining about method length and we had no need for that particular collection.
=> HT-2621 Confirm UCM HTItems are treated as any other

lib/enum_chron.rb, lib/holding.rb, lib/ht_item.rb, lib/multi_part_overlap.rb, spec/enum_chron_spec.rb, spec/holding_spec.rb, spec/ht_item_spec.rb, spec/multi_part_overlap_spec.rb
- HTItems with n_enum were matching those without, but not the reverse.
- n_enum and n_chron default to "" instead of nil
=> Bugfix: HTItems w/o n_enum match all other items

.rubocop_todo.yml, bin/compile_cost_reports.rb, lib/cluster.rb, lib/cluster_overlap.rb, lib/cost_report.rb, lib/ht_item_overlap.rb, lib/multi_part_overlap.rb, lib/overlap.rb, spec/cluster_overlap_spec.rb, spec/cluster_spec.rb, spec/compile_cost_reports_spec.rb, spec/cost_report_spec.rb, spec/overlap_report_spec.rb
- compiles ec=>org and org=>ec data structures in Cluster objects
- removes dependence on ClusterOverlap and overlap records for cost report generation
- simple conditional in HtItemOverlap for computing item/holding overlap
Processes ~740 access:deny items per second so roughly a 4 hour run of 10m items.   
ETAS and the other overlap report likely have performance problems due to its reliance on:
* ClusterOverlap
* MultiPartOverlap
* SinglePartOverlap
* SerialOverlap
=> HT-2717 improve perf of Cost Report generation

.github/workflows/build-master.yml, .github/workflows/ci.yml, .github/workflows/tag-release.yml
Cribbed from https://github.com/mlibrary/patron_account/blob/main/.github/workflows
@daaang Is the plan to at some point factor this out to actions shared under the "phineas" brand? As is, I'm a little worried about the potential for meaningless arbitrary variation between repositorie and/or a bunch of stuff that nobody fully understands or commits to owning (à la the capistrano installs), or is this relatively minimal enough that the duplication across repositories isn't a big deal? Certainly https://github.com/mlibrary/patron_account/blob/main/.github/workflows/deploy-testing.yaml at least seems like it would benefit from abstraction (not duplicating it here since there's no deployment as such to roll out yet..)
=> HT-2754 - automatically publish docker image

lib/cluster.rb
The following methods in the Cluster class were untested and unused.
Likely remnants of approaches discarded or refactored.
* merge
* merge_many
* self.merge_many
* add_ocns
* billing_entities
=> Remove deprecated methods from Cluster

.rubocop_todo.yml, bin/add_print_holdings.rb, lib/calculate_format.rb, lib/cluster.rb, lib/cluster_getter.rb, lib/cluster_holding.rb, lib/holding_loader.rb, lib/large_cluster_error.rb, lib/large_clusters.rb, lib/reclusterer.rb, lib/services.rb, spec/calculate_format_spec.rb, spec/cluster_holding_spec.rb, spec/cost_report_spec.rb, spec/fixtures/large_clusters.rb, spec/large_clusters_spec.rb, spec/overlap_report_spec.rb, spec/spec_helper.rb
* Services.large_clusters is little more than a list of OCNs
* ClusterHolding.update prevents cluster.large? from having more than 1 holding per member
* Does NOT resolve cases where there are already multiple holdings per member
* Does NOT prevent duplication in merged clusters
* CalculateFormat returns "ser" when cluster.large?
=> Prevent duplicate holdings in large clusters

bin/renormalize_enumchrons.rb, lib/cluster.rb, lib/enum_chron.rb, lib/enum_chron_parser.rb, lib/holding.rb, lib/ht_item.rb, lib/ht_item_overlap.rb, lib/multi_part_overlap.rb, spec/cluster_spec.rb, spec/enum_chron_spec.rb, spec/holding_spec.rb, spec/ht_item_overlap_spec.rb, spec/multi_part_overlap_spec.rb, spec/renormalize_enum_chron_spec.rb
n_enum_chron = [n_enum, n_chron].join(" ").sub(/^ $/, '')
Uses of n_enum for comparison have been replaced by n_enum_chron.
=> HT-2771 combine n_chron/n_enum for matching purposes

lib/cost_report.rb
Hathitrust gets some IC costs assigned to it that need to be distributed to the members as "extra". 
This is a one line change that removes 'hathitrust' from the list of ht_members when calculating the extra_per_member.
=> Calc extra per member

lib/cluster.rb, lib/ht_item_overlap.rb, lib/multi_part_overlap.rb, spec/cluster_spec.rb, spec/ht_item_overlap_spec.rb, spec/multi_part_overlap_spec.rb
After further review it was discovered that the existing print holdings process only uses normalized enum and not both enum and chron. This changes matching back to using only "n_enum", but keeps the n_enum_chron attribute in place.
=> HT-2771: revert mpm matching to only use n_enum

bin/compile_cost_reports.rb, lib/calculate_format.rb, lib/cost_report.rb, spec/calculate_format_spec.rb, spec/compile_cost_reports_spec.rb
* also makes explicit in spec that shared bib_id not cluster is req'd for mpm item format contagion.
=> Calc cost rpt on item format not cluster format

bin/export_overlap_report.rb, lib/overlap.rb, spec/overlap_report_mysql_import_spec.rb, spec/overlap_report_spec.rb, spec/overlap_spec.rb, sql/003_holdings_htitem_htmember.sql
Edits bin/export_overlap_report.rb and lib/overlap.rb. Adds columns `lock_id` and `n_enum` to `holdings_htitem_htmember` table. 
I don't know what bin/export_etas_overlap_report.rb or lib/etas_overlap.rb are for.
=> HT-2900: Add n_enum and lock_id to overlap reports

bin/export_overlap_report.rb, lib/cluster.rb, spec/cluster_spec.rb, spec/overlap_report_spec.rb
This adds the field `last_modified` to Clusters and sets as Time.now.utc with a before_save callback. This may be the wrong name for it, as a save doesn't guarantee modification. 
Without a way to filter clusters of interest, consuming services will need to process the entire database. That's acceptable when we are performing monthly updates, but not so when we are performing updates at much higher frequency. 
edit: I should note that this doesn't deal with deletes, although in practice this shouldn't be too much of an issue.
=> Add cluster last modified

lib/cluster.rb, lib/cluster_holding.rb, lib/cluster_ht_item.rb, lib/holding.rb, spec/cluster_holding_spec.rb, spec/cluster_ht_item_spec.rb, spec/cluster_ocn_resolution_spec.rb, spec/factories/holding.rb, spec/factories/ht_item.rb, spec/holding_spec.rb
See #86 ; merge after #86  / #88. Only relevant commit here is https://github.com/hathitrust/holdings-backend/pull/89/commits/7f882b4cacbaba32913f8b9572b3d5572f8372d8
- Adds tests for ensuring last modified changes when adding or updating
holdings, ocn resolution, ht items
- Only updates an ht item if something has actually changed
=> HT-2970 / HT-2940: Update last_modified iff something has changed

bin/run_estimate.sh
I realized the wrapper for the estimate script 1) didn't do anything, 2) wouldn't have worked even if it did anything
=> Fix run estimate wrapper

bin/inspect_ocn.rb, lib/member_holding.rb, lib/member_holding_file.rb, spec/member_holding_file_spec.rb, spec/member_holding_spec.rb
Based on:
https://tools.lib.umich.edu/confluence/display/HAT/Print+Holdings%3A+Options+for+Multiple+OCNs
https://github.com/hathitrust/holdings-backend/blob/master/adr/0004-order-independence.md
... and the fact that a submitted holdings record with multiple OCNs previous to this fix comes through as an array of numbers, which upon loading gets interpreted as 0 and eventually causing a Mongo::Error::MaxBSONSize
It used to be:
```
Autoscrub input:  ocn1,ocn2 \t ...
Autoscrub output: {"ocn":[1,2], ...} <<-- root of problem
Loader internal: {"_id"=>BSON::ObjectId(...), "ocn"=>0, ...}
```
But now it is:
```
Autoscrub input:  ocn1,ocn2 \t ...
Autoscrub output: {"ocn":1, ...}
Autoscrub output: {"ocn":2, ...}
Loader internal: {"_id"=>BSON::ObjectId(...), "ocn"=>1, ...}
Loader internal: …
```
=> Autoscrub multi OCN

bin/load_concordance_diffs.rb, lib/ocn_concordance_diffs.rb
There were a few bugs in `bin/load_concordance_diffs.rb`. Also needed to set a larger batch size for logging.
=> Load concordance diffs

bin/compile_cost_reports.rb
Couldn't run cost report on k8s because the requires were in the wrong order.
=> cannot load services before /lib/

bin/delete_holdings_by_uuid.rb
Takes path(s) to file(s) with lines of: 
ocn \t org \t holdings.uuid
and delete matching holdings
Usage: bundle exec ruby bin/delete_holdings_by_uuid.rb file_with_holdings.tsv
=> script for HT-3037, to remove unr & unsw

bin/get_holdings_uuid_by_org.rb, lib/basic_query_report.rb
So I can get all holdings to file, so I can split them up and let loose a bunch of pods and delete them.
=> script to get all holdings for 1+ member(s)

bin/full_etas_overlap.rb, bin/update_overlap_table.rb, kube/lib/holdings/config.libsonnet, kube/lib/holdings/holdings_cronjobs.libsonnet, lib/cluster.rb, lib/holding.rb, lib/multi_part_overlap.rb, lib/overlap.rb, lib/serial_overlap.rb, lib/single_part_overlap.rb, spec/cluster_spec.rb, spec/multi_part_overlap_spec.rb, spec/update_overlap_table_spec.rb, sql/003_holdings_htitem_htmember.sql
Caches cluster level counts. Could still be done for MPMs.
=> HT-3026: Nightly etas overlap updates

Gemfile, Gemfile.lock, lib/cluster_holding.rb, lib/holding.rb
Changes to ClusterHolding, specifically to the methods check_for_duplicate_uuids! and find_old_holdings, in order to improve speed when adding holdings.
=> faster lookup of holdings

bin/compile_estimated_IC_costs.rb
In addition to the IC cost, this adds information about the number of unique OCNs and the count/percent of matches. In the old system we also reported the number of usable holdings (MPM, SPM, SER), but that is not readily available to `bin/compile_estimated_IC_costs.rb` because it is only given a list of OCNs.
=> HT-3072 add narrative and stat tracking to estimate generation

bin/append_sheets.pl, bin/cost_changes.sh, bin/get_all_members.rb
This time without a buncha commits from other branches!
Copied and modified from https://github.com/hathitrust/print_holdings, a couple of scripts that look at old cost reports and generates 3 files:
1. A history of total-cost per member per report
2. A history of total-cost diff (month to month) per member per report
3. A history of total-cost diff percentage (month to month) per member per report
These all go into the finished product, the Google Sheet, as separate tabs.
=> added scripts for generating cross-costreport comparisons

bin/prep_loadfiles.sh
As long as we're working with HT003, this way we'll have something shared in the master branch, and I have something to document for https://tools.lib.umich.edu/jira/browse/HT-3063 .
=> temp solution for prepping HT003-files

lib/ocn_concordance_diffs.rb, spec/ocn_concordance_diffs_spec.rb
Also fixes a namespace bug that was not caught by the specs.
=> Change location of concordance diffs to concordance/diffs

bin/reports/compile_cost_reports.rb, bin/reports/compile_estimated_IC_costs.rb, bin/reports/export_etas_overlap_report.rb, bin/reports/export_overlap_report.rb, bin/reports/full_etas_overlap.rb, lib/report/estimate_ic.rb, lib/report/etas_member_overlap_report.rb, lib/report/overlap_report.rb, spec/report/estimate_ic_spec.rb, spec/report/etas_member_overlap_report_spec.rb, spec/report/overlap_report_spec.rb
Pulling logic out of bins into lib/report and adding some specs. 
lib/report/overlap_report.rb and bin/reports/export_overlap_report.rb appear to be unnecessary. They are the single member special case of the full_etas_overlap. I didn't do much with full_etas_overlap as it is already very simple.
=> Ht 3115 refactor reports

bin/get_all_members.rb, lib/clusterable/holding.rb, lib/data_sources.rb, lib/data_sources/holdings_db.rb, lib/data_sources/ht_collections.rb, lib/data_sources/ht_members.rb, lib/data_sources/large_clusters.rb, lib/data_sources/serials_file.rb, lib/services.rb, spec/data_sources/holdings_db_spec.rb, spec/data_sources/ht_collections_spec.rb, spec/data_sources/ht_members_spec.rb, spec/data_sources/large_clusters_spec.rb, spec/fixtures/collections.rb, spec/fixtures/large_clusters.rb, spec/fixtures/members.rb, spec/report/cost_report_spec.rb, spec/update_overlap_table_spec.rb
I chose the name `DataSources`, since each of the moved things represents a source of data external to the application. The first commit makes the logical change and should be reasonably readable; the second changes indentation to appease rubocop so looks like a larger change than it is.
=> HT-3118: Namespace services

Dockerfile, bin/add_ht_items.rb, bin/add_print_holdings.rb, bin/compare_clusters.rb, bin/concordance_validation/validate.rb, bin/concordance_validation/validate_and_delta.rb, bin/daily_add_ht_items.rb, bin/delete_holdings_by_uuid.rb, bin/get_all_members.rb, bin/get_holdings_uuid_by_org.rb, bin/inspect_ocn.rb, bin/load_concordance_diffs.rb, bin/pry_shell.rb, bin/renormalize_enumchrons.rb, bin/reports/compile_cost_reports.rb, bin/reports/compile_estimated_IC_costs.rb, bin/reports/compile_member_counts_report.rb, bin/reports/export_etas_overlap_report.rb, bin/reports/export_overlap_report.rb, bin/reports/full_etas_overlap.rb, bin/update_overlap_table.rb, lib/basic_query_report.rb, lib/scrub/autoscrub.rb, lib/scrub/max_ocn.rb, lib/tasks/build_database.rb, spec/spec_helper.rb
This should ensure we can consistently run scripts under bin as bundle
exec ruby bin/whatever.rb
- Add RUBYLIB to Dockerfile
- Remove $LOAD_PATH manipulation
- Remove bundler/setup -- we were not using it consistently; scripts are
generally started with bundle exec ruby bin/whatever.rb. In the future,
if we have a single CLI wrapper, we may want to make sure we can call it
without needing to use bundle exec.
=> Make load path / bundle stuff consistent

lib/enum_chron_parser.rb
Not a solution to the problem, but a change to make the warnings make more sense.
=> Ht 3192 enumbug

.rubocop_todo.yml, lib/etas_overlap.rb, lib/reports/etas_organization_overlap_report.rb, spec/etas_overlap_spec.rb, spec/reports/etas_organization_overlap_report_spec.rb
HT-3198 through HT-3201. This will fail specs until it is rebased. HT-3061 makes changes to ht_organizations vs ht_members so merging that first will save some duplicative work here.
=> Overlap report revisions

bin/add_shared_print_commitments.rb, lib/cluster.rb, lib/clusterable/commitment.rb, lib/clustering/cluster_commitment.rb, lib/loader/shared_print_loader.rb, spec/clusterable/commitment_spec.rb, spec/clustering/cluster_commitment_spec.rb, spec/clustering/cluster_getter_spec.rb, spec/factories/commitment.rb, spec/loader/shared_print_loader_spec.rb
Doesn't address updates or deprecations, or even identity (there are a lot of duplicates in the existing database). 
My only concern before loading is the setting of `cluster.last_modified` when adding commitments, which seems unnecessary.
=> Clusterable Shared Print Commitments and loader

lib/reports/etas_organization_overlap_report.rb, spec/reports/etas_organization_overlap_report_spec.rb
Incomplete ETAS overlap reports were being generated for organizations when a different organization was requested. When a particular organization was NOT requested, all were being generated correctly.
=> HT-3216: bugfix write report only for org reqd

.rubocop_todo.yml, bin/holdings_deleter.rb, lib/overlap/overlap_table_update.rb, lib/utils/session_keep_alive.rb, spec/holdings_deleter_spec.rb, spec/spec_helper.rb, spec/utils/session_keep_alive_spec.rb
Broke out some code from `lib/overlap/overlap_table_update.rb` into new class `lib/utils/session_keep_alive.rb`, since the same thing was needed to keep the holdings deleter from crashing with an expired cursor.
@jsteverman and I tried to think what a (useful && non-production) test for this would look like. `overlap_table_update.rb` does not directly test this behavior.
Any ideas from @aelkiss or the Universe appreciated.
=> New class Utils::SessionKeepAlive: for keeping sessions alive

lib/clusterable/commitment.rb, spec/clusterable/commitment_spec.rb
`def deprecate` was untested and failing.
=> Test and fix Clusterable.new.deprecate

.rubocop_todo.yml, Dockerfile, Dockerfile.prod, bin/add_print_holdings.rb, bin/reports/export_etas_overlap_report.rb, config/settings.yml, lib/reports/etas_organization_overlap_report.rb, spec/reports/etas_organization_overlap_report_spec.rb
bin/add_print_holdings.rb and bin/reports/export_etas_overlap_report.rb will fail in production.
They need the environment variable RCLONE_CONFIG_PATH set to rclone.conf secret?
=> Ht 3095 automate etas overlap

Dockerfile
I've been using `entr` for developing, Sandi Metz style, but have had to keep it in a local modified Dockerfile.
Also I find it super frustrating to not have `less` available.
Can we just add them to the Dockerfile?
=> add less and entr to Dockerfile

config/environments/test.yml, config/settings.yml, lib/reports/etas_organization_overlap_report.rb
I put `50` in the settings mostly on a whim.
=> ETAS Overlap: Limit batch size to avoid CursorNotFound

bin/reports/compile_cost_reports.rb
One line change.
I just think it's too much having the progress tracker log something every 1K lines.
Costreport logs are all:
> I, [2022-02-14T20:36:18.565935 #7]  INFO -- :  10_609_000. This batch 1_000 in  0.5s (2_019 r/s). Overall 766 r/s.
> I, [2022-02-14T20:36:19.038463 #7]  INFO -- :  10_610_000. This batch 1_000 in  0.5s (2_115 r/s). Overall 766 r/s.
> I, [2022-02-14T20:36:19.362272 #7]  INFO -- :  10_611_000. This batch 1_000 in  0.3s (3_088 r/s). Overall 766 r/s.
> I, [2022-02-14T20:36:19.699485 #7]  INFO -- :  10_612_000. This batch 1_000 in  0.3s (2_965 r/s). Overall 766 r/s.
> I, [2022-02-14T20:36:20.010105 #7]  INFO -- :  10_613_000. This batch 1_000 in  0.3s (3_219 r/s). Overall 766 r/s.
=> log every 50K lines instead of every 1k lines

bin/add_print_holdings.rb
Automatic reporting is not desired in bin/add_print_holdings.rb, at least not the way it is currently being used.
=> removed automatic reporting

config/environments/test.yml, lib/shared_print/finder.rb, lib/shared_print/update_record.rb, lib/shared_print/updater.rb, lib/utils/tsv_reader.rb, spec/fixtures/test_sp_update_file.tsv, spec/shared_print/finder_spec.rb, spec/shared_print/update_record_spec.rb, spec/shared_print/updater_spec.rb, spec/utils/tsv_reader_spec.rb
New code for updating shared print commitments:
Give a file to `SharedPrint::Updater` and it'll go through each line, turn line into a `SharedPrint::UpdateRecord`, use `SharedPrint::Finder` to find a matching `Clusterable::Commitment` and update it if conditions are right.
=> update shared print commitments

lib/keio_updater.rb, spec/keio_updater_spec.rb
A one-off script for updating ht_items that have `collection_code: "KEIO", billing_entity: "hathitrust"` to `billing_entity: "hathitrust"`.
Can be removed once used, assuming we never need it again.
=> update keio ht_items

bin/report/compile_estimated_IC_costs.rb
Consistent rounding for percentage, added missing $-symbol, added missing %-symbol.
Before:
```
Total Estimated IC Cost:411.2486604957148
In all, we received 146214 distinct OCLC numbers.
Of those distinct OCLC numbers, 69714 (47.7%) match in
HathiTrust, corresponding to 154449 HathiTrust items.
Of those, 28776 ( 18.6%) are in the public domain,
125673 ( 81.36860711302761 ) are in copyright.
```
After:
```
Total Estimated IC Cost: $411.25
In all, we received 146214 distinct OCLC numbers.
Of those distinct OCLC numbers, 69714 (47.7%) match in
HathiTrust, corresponding to 154449 HathiTrust items.
Of those, 28776 (18.6%) are in the public domain,
125673 (81.4%) are in copyright.
```
=> slight changes to the formatting of estimate output

lib/shared_print/replacer.rb
When called from `Replacer`, `Finder` needs to not care about `deprecation_status`.
=> Deprecated commitments must be included

bin/cost_changes.sh
Cost report generation (the historical tabs you get from running `bin/cost_changes.sh`) was broken, after `bin/get_all_members.rb` got subsumed by `phctl.rb`.
=> updated `bin/cost_changes.sh` to use `phctl members`

bin/setup/setup_dev.sh, docker-compose.yml
Some scripts in dev failed because the pushgateway was not started by
default or referenced by development config. This starts and enables it.
=> Use pushgateway in dev

bin/phctl.rb, lib/reports/rare_uncommitted.rb, spec/reports/rare_uncommitted_spec.rb
(Doing some changes to reflect changes in the requirements.)
This is a report that gets a bunch of clusters, based on some fixed criteria (in `@query`) and a number of criteria parameters (`@max_h, @max_sp_h, @non_sp_h_count, @commitment_count, @organization` that can be set in the `phctl` call).
The data is presented either as condensed counts, by default, or as a list of matching holdings for an organization if given `@organization`.
`run()` does most of the heavy lifting and gets the clusters which both report flavors are based upon, while `output_counts()` and `output_organization()` do the appropriate formatting.
=> Rare uncommitted 2

bin/phctl.rb, config/settings.yml, lib/reports/etas_organization_overlap_report.rb, spec/reports/etas_organization_overlap_report_spec.rb
Adds a step to the generation of the ETAS overlap reports. It now writes to a local directory by default. Once completed, the gz files are copied to the /htprep and dropbox locations.
=> Write ETAS rpts local, cp .gz to persistent storage

sql/003_holdings_htitem_htmember.sql
The n_enum column was defined as VARCHAR(50). In the hathifiles there are ~24k unique description fields longer than that. The max length in the Hathifiles is 200 characters; probably some other system truncating there. 
At one point the holdings_htitem_htmember table was truncating long n_enums and presumably lock_ids. I suspect recent updates have turned strict mysql on, resulting in errors rather than truncating and warning. 
This will of course need to be applied to the actual database, something like. 
ALTER TABLE ht_repository.holdings_htitem_htmember MODIFY lockid VARCHAR(300);
ALTER TABLE ht_repository.holdings_htitem_htmember MODIFY n_enum VARCHAR(250);
I don't know what the implications are for the lock_ids not matching. Was that a problem before? Does fixing them introduce a …
=> Increase length limit on holdings_htitem_htmember table

lib/clusterable/holding.rb, lib/clusterable/ocn_resolution.rb
mongoid 7.4.0 has a couple of changes that require this:
https://github.com/mongodb/mongoid/commit/8a821e44bf8279890cab5012c2dda7f8e5dbb34f (change in how === works)
https://github.com/mongodb/mongoid/commit/a8f4484a35c4ad0e362c218668f4f81844453e38 (change in how it's collecting embedded documents for change tracking when persisting)
Both of these together mean that when saving a document, it checks with
== against other embedded documents to see if it's already encountered
it, and their classes might not match, so our overridden == should
return false in such a case rather than throwing an exception.
=> Allow comparing clusterables of different classes

lib/services.rb, spec/utils/push_metrics_marker_spec.rb
Noticed that the invocation for `Prometheus::Client::Push` had changed when trying to load new holdings.
This change came with the bumping of prometheus-client from 2.1.0 to 4.0.0 (https://github.com/hathitrust/holdings-backend/commit/89df3f1f08fd6356e21bd2ac614d80b16a19033a#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL59)
=> test and fix for broken invocation of prometheus pushgateway in Services

lib/scrub/chunker.rb, spec/fixtures/pre_chunk.tsv, spec/scrub/chunker_spec.rb
A ruby wrapper around system calls to sort & split, for the specific purpose of splitting scrubbed files into several sorted files so they can be loaded in parallel. 
For https://hathitrust.atlassian.net/browse/DEV-359, a child task of https://hathitrust.atlassian.net/browse/DEV-299.
=> code for chunking in ruby (ish)

config/environments/test.yml, lib/utils/file_transfer.rb, lib/utils/file_transfer_error.rb, spec/utils/file_transfer_spec.rb
For https://hathitrust.atlassian.net/browse/DEV-358, a child task of DEV-299.
A file transfer class that simplifies uploading/downloading to/from local storage and dropbox.
Essentially just a wrapper for `rclone` system calls.
=> file transfer class for DEV-358

lib/data_sources/directory_locator.rb, spec/data_sources/directory_locator_spec.rb
`DataSources::DirectoryLocator` knows about the directories (local or remote, it don't care) where a member's holdings, shared print & analysis files reside.
=> Dev 360, adding DirectoryLocator

lib/reports/oclc_registration.rb, lib/reports/rare_uncommitted.rb, spec/reports/oclc_registration_spec.rb, spec/reports/rare_uncommitted_spec.rb
DEV-250:
* change a column header
* add 2 overlap-count columns (Weltin wanted 3 but the 3rd one is a whole nother thing that we spun off into a separate ticket https://hathitrust.atlassian.net/browse/DEV-412 for later)
DEV-361: 
* change oclc_sym lookup to be case-insensitive
* format dates into %Ymd format, no delimiters
* change raise-message for when the path to the oclc_sym_collection_map is missing
=> Small fixes for Shared Print reports (DEV-250, DEV-361)

bin/load_test_data.sh, bin/setup/setup_dev.sh, bin/sidekiq_web.ru, config/initializers/sidekiq.rb, config/mongoid.yml, config/settings.yml, docker-compose.yml, lib/services.rb, lib/sidekiq_jobs.rb, spec/spec_helper.rb
* Add location for sidekiq/redis configuration
* Expose more configuration for mongodb -- holdings-testing / mongo 5 needed some different options here
sidekiq-web still isn't working, I suspect because the inline config overrides the provided config in the sidekiq initializer.
=> Configuration for sidekiq

lib/shared_print/update_record.rb, lib/shared_print/updater.rb, spec/shared_print/updater_spec.rb
Problem: You cannot update `local_id` or `ocn` with the existing shared print update-script.
Solution: Now, in order to update `local_id` and/or `ocn`, add the columns `new_local_id` and/or `new_ocn` to the update file, like:
```
organization  |ocn       |local_id           |new_ocn
bu            |8061382   |99193019080001161  |898915865
bu            |6785135   |99191292180001161  |263616332
bu            |4738078   |99177938200001161  |76925351
```
The "new_" prefix helps us distinguish the update field (`new_local_id`, `new_ocn`) from the lookup field (`local_id`, `ocn`).
Pass to `phctl sp update <file>` as before.
=> fix for DEV-454

bin/sidekiq_web.ru, config/initializers/sidekiq.rb, lib/services.rb
- inline configuration when using redis sentinel (rather than putting in ht_tanka)
- ensure sidekiq web doesn't clobber existing redis configuration
Basically, we put the configuration we want in `Services.redis_config` and can get at it / modify it there as needed; the default if we try to use it without configuring it is to raise an exception. The `Sidekiq.configure_server` / `Sidekiq.configure_client` blocks are basically setting up callbacks to tell Sidekiq where to get the configuration from when it needs it rather than providing it directly.. this is just the style of configuration that Sidekiq (and many other Ruby gems like rspec) use, but it does make things a bit more confusing
=> DEV-405, DEV-424: sidekiq/redis configuration

lib/loader/holding_loader.rb, lib/phctl.rb, lib/scrub/chunker.rb, lib/scrub/scrub_runner.rb, lib/utils/file_transfer.rb, spec/integration_spec.rb, spec/scrub/scrub_runner_spec.rb
This PR adds `Sidekiq::Batch` to `Scrub::ScrubRunner`.
When a batch completes it triggers some cleanup (done by `Loader::HoldingLoader::Cleanup`), and we have to fake this in testing (where sidekiq is not running), hence the `force_holding_loader_cleanup_test` stuff.
=> getting scrubrunner to batch load with sidekiq

.github/workflows/ci.yml, .gitignore, .rspec, bin/setup/setup_test.sh, docker-compose.yml, lib/services.rb, lib/sidekiq_jobs.rb, lib/utils/push_metrics_marker.rb, spec/utils/push_metrics_marker_spec.rb
With the old version of prometheus client, metrics that we had registered but not actually set a value for did not get sent to the push gateway. With the newer version, they do, which reset last success time & expected success interval to '0' at every job start, which caused spurious alerts.
This version substantially changes how metrics & the specs work. Now, metrics are lazily registered by the push metrics marker when they are actually needed. This also removes some of the stubbing in the specs for prometheus stuff while adding integration tests to ensure that pushing to the push gateway does actually work.
In doing this I found that the behavior in rspec with various hooks running at spread-out times got pretty confusing esp. regarding stubbing the push gateway and at what time that …
=> fix push metrics

lib/shared_print/deprecation_record.rb, spec/shared_print/deprecation_record_spec.rb
All it does inspect a variable that was previously not inspected, when raising a particular error.
=> fix for bug DEV-423, add `.inspect` to a `SharedPrint::DeprecationError` message

lib/reports/estimate.rb
I prefer having classes bail from initialize or validate if crucial settings are missing. 
Makes the error much clearer and imho encourages defensive coding.
=> estimate script crashes if missing crucial setting 

lib/cluster.rb
This change ensures that when OCNs in a cluster change, we only use the OCNs for the resolutions and the htitems. In normal usage, holdings should never end up in the "wrong" cluster. However, a small number of shared print commitments had their OCNs changed without moving clusters, leading to inconsistent clusters. This update mitigates the effect of that. DEV-504 will address the underlying issue.
=> DEV-505: Only use resolutions & htitems when updating OCNs

lib/scrub/autoscrub.rb, lib/scrub/ocn_candidate.rb, spec/scrub/ocn_candidate_spec.rb
Autoscrub would previously crash if given an OCN without a numeric part.
=> fail more gracefully if ocn.nil?, DEV-513

lib/scrub/scrub_runner.rb, spec/scrub/scrub_runner_spec.rb
It used to be the case that if one of the files being scrubbed broke the "no greater/smaller diff than x" rule, the whole scrub session crashed out because exceptions were not caught properly. This fixes that.
=> DEV-515, handle scrubbing file that has a bigger diff than we like without crashing

lib/scrub/chunker.rb, spec/scrub/chunker_spec.rb
Updated sort call & associated test.
Changed from `sort -s -n -k1,1` to `sort -t: -k2,2 -s -n`, so that we are actually sorting on the OCN numerically.
=> DEV-518: Chunked files were not sorted numerically by OCN. Fix for that.

lib/reports/cost_report.rb, spec/integration_spec.rb
Making sure cost reports are named the way they used to be and placed in the right subdirectory.
=> changed back costreport output path

lib/phctl.rb, spec/phctl_spec.rb
Most don't know how to handle it
=> Don't pass --inline option through to common job

lib/mongo_updater.rb, spec/mongo_updater_spec.rb
To address cases where we want to do a mass-update and don't want to deserialize-serialize every document.
=> Adding class for mass-update of embedded documents in mongo

lib/reports/rare_uncommitted.rb, lib/shared_print/groups.rb, spec/reports/rare_uncommitted_spec.rb, spec/shared_print/groups_spec.rb
Added shared print groups and related overlap column in the rare_uncommitted report.
Now if you run a rare_uncommitted report for an organization that is one of the `SharedPrint::Groups`, you get the additional column "overlap_group" which counts how many of the other members in your group(s) have holdings on the same cluster.
=> DEV-412, shared print overlap groups

lib/clusterable/commitment.rb, lib/loader/shared_print_loader.rb, lib/utils/tsv_reader.rb, spec/clusterable/commitment_spec.rb, spec/fixtures/sp_commitment_policies.tsv, spec/integration_spec.rb, spec/loader/shared_print_loader_spec.rb, spec/utils/tsv_reader_spec.rb
Adding new shared print policy `NON-REPRO` (formerly hypothesized as `do not reproduce`) and some associated tests.
For context: `policies` is an array field on `Clusterable::Commitments` that may take a number of different values.
We expect to get it from members in the form of a comma-separated text field in a `.tsv` file.
=> DEV-523, `NON-REPRO` policy for commitments

lib/phctl.rb, lib/shared_print/phase_3_validator.rb, lib/sidekiq_jobs.rb, phctl.sh, spec/fixtures/phase_3_commitments.tsv, spec/integration_spec.rb, spec/phctl_spec.rb, spec/shared_print/phase_3_validator_spec.rb
Implementing the phase 3 commitments validator that DEV-464 implies.
`SharedPrint::Phase3Validator` can take a file of commitments and load the ones that meet the criteria set forth in `pass_validation?`.
=> DEV-464, a validator for phase 3 sp commitments

lib/clusterable/commitment.rb, lib/shared_print/phase_3_validator.rb, lib/shared_print/update_record.rb, spec/shared_print/phase_3_validator_spec.rb, spec/shared_print/updater_spec.rb
Per https://hathitrust.atlassian.net/browse/DEV-465 we should reject a commitment if it has both `NON-REPRO` & `DIGITIZEONDEMAND`, as these are mutually exclusive.
This goes both for adding new commitments as for updating existing ones.
=> Added policy validation rule from DEV-465

Dockerfile, lib/scrub/autoscrub.rb, lib/utils/encoding.rb, spec/fixtures/non_valid_utf8.txt, spec/fixtures/valid_utf8.txt, spec/scrub/auto_scrub_spec.rb, spec/utils/encoding_spec.rb
New class `Utils::Encoding` for checking if a file contains illegal utf8 sequences.
`Scrub::AutoScrub` uses it to check incoming files before subjecting them to further analysis.
`Utils::Encoding` has the ability to force_utf8 and remove illegal sequences (but that's not in use yet, if ever).
=> Before scrubbing file, make sure it has no illegal utf8 stuff

Dockerfile.prod
It was there in `Dockerfile` but when trying to use `uchardet` in production I realized I hadn't added it to `Dockerfile.prod`.
=> Added uchardet to Dockerfile.prod

lib/scrub/autoscrub.rb, spec/integration_spec.rb, spec/scrub/scrub_runner_spec.rb
Scrub logs were seeping into each other. 
Uploaded log files had a different timestamp format than we require from the input files, so I harmonized that to all be YYYYMMDD (no dashes) so as to be pleasurable to the eye while I was at it.
=> DEV-632: changed scrub logging to prevent seepage, changed timestamp format on scrub log filename

config/environments/test.yml, spec/concordance_validation/delta_spec.rb, spec/data_sources/directory_locator_spec.rb, spec/data_sources/holdings_db_spec.rb, spec/file_mutex_spec.rb, spec/integration_spec.rb, spec/loader/hathifile_spec.rb, spec/ocn_concordance_diffs_spec.rb, spec/phctl_spec.rb, spec/reports/cost_report_spec.rb, spec/reports/estimate_spec.rb, spec/reports/etas_organization_overlap_report_spec.rb, spec/reports/member_counts_spec.rb, spec/scrub/auto_scrub_spec.rb, spec/scrub/chunker_spec.rb, spec/scrub/member_holding_spec.rb, spec/scrub/record_counter_spec.rb, spec/scrub/scrub_runner_spec.rb, spec/shared_print/deprecator_spec.rb, spec/shared_print/phase_3_validator_spec.rb, spec/spec_helper.rb, spec/utils/encoding_spec.rb, spec/utils/file_transfer_spec.rb, spec/utils/line_counter_spec.rb
- creates a temporary directory just for that test; puts it in ENV["TEST_TMP"]. This means we can avoid cleanup in each test
- reloads settings to point to that tmpdir; reloading settings before each test also means we don't have to worry about saving/restoring settings in individual specs
- Enable disabled autoscrub JSON spec
=> DEV-406: Use temporary directories for test

lib/clustering/cluster_holding.rb, lib/loader/holding_loader.rb, lib/reports/commitment_replacements.rb, lib/reports/cost_report.rb, lib/reports/estimate.rb, lib/reports/etas_organization_overlap_report.rb, lib/reports/rare_uncommitted.rb, lib/reports/uncommitted_holdings.rb, lib/shared_print/deprecator.rb, lib/shared_print/phase_3_validator.rb, lib/shared_print/replacer.rb, lib/shared_print/updater.rb
As far as I can tell, `Loader::HoldingLoader.item_from_line` is _the_ thing being called once for each line in the input file being loaded. If `Thread.pass` needs to be sprinkled in more places, I'm not seeing it.
=> DEV-569: Adding `Thread.pass` to get rid of Sidekiq warnings when loading holdings

generate_documentation.sh, lib/scrub/autoscrub.rb, lib/scrub/member_holding_file.rb, lib/utils/encoding.rb, spec/scrub/auto_scrub_spec.rb, spec/utils/encoding_spec.rb
Changes mostly involve `Util::Encoding.force_utf8` which already existed but wasn't really plugged in.
It used to be that when `Scrub::AutoScrub` encountered a file with non-utf8 strings it would report what the encoding was and give up. This led to way too much back and forth between members. 
`Util::Encoding` now `iconv`s to a new file and does a `diff` between the old (non-valid) and the new (valid) files, so that the changes can be reported to the scrub log in `Scrub::AutoScrub.run`, and proceeds with the new (valid) file.
=> DEV-659: Convert input files to utf8 and log changes, when scrubbing

lib/reports/shared_print_newly_ingested.rb
Diff, essentially:
```
- w
+ W
```
That is to say, what has functionally changed is a non-interpolating `%w[...]` was changed into an interpolating `%W[...]`. The changed code was broken out into its own method (`query`) so I could write a simple test to make it obvious that interpolation happened.
=> Dev-550: (bugfix) Making sure variable is used properly in query

Dockerfile, lib/clusterable/commitment.rb, lib/loader/shared_print_loader.rb, lib/shared_print/phase_3_validator.rb, spec/shared_print/phase_3_validator_spec.rb
The (user facing) specs say you can submit commitments with the field `other_commitments`, and that field did exist, but the commitments loader had no code that knew how parse that field.
This PR adds capability to deal with `other_commitments`.
=> SPO-41: make SharedPrint::Phase3Validator support other_commitments

lib/shared_print/phase_3_validator.rb, spec/shared_print/phase_3_validator_spec.rb
Phase 3 commitments should all have the same `committed_date`. Set as they are being parsed by `phase_3_validator.rb`.
=> Default date for phase 3 commitments

bin/inspect_ocn.rb, lib/cluster.rb, lib/clusterable/commitment.rb, lib/shared_print/finder.rb, lib/shared_print/phase_3_validator.rb, lib/shared_print/phase_updater.rb, lib/shared_print/phases.rb, lib/shared_print/select_distinct_phases.rb, spec/fixtures/shared_print_umich_phase123.json, spec/reports/phase3_oclc_registration_spec.rb, spec/shared_print/finder_spec.rb, spec/shared_print/phase_3_validator_spec.rb
Problem (https://hathitrust.atlassian.net/browse/DEV-573): 
We are currently using `committed_date` to determine which "phase" a commitment belongs to. Meaning, when we want to e.g. look up commitments in phase 3, we have to look up "what's the date associated with phase 3" and query on that committed_date. This, in combination with sloppy date formatting and servers in different timezones, has led to issues with timezone confusion.
Proposed solution: 
* We add an integer field called `phase` to `lib/clusterable/commitment.rb`. 
* Keep `committed_date`, but don't use it as a proxy for phase.
* Write and run a piece of single-use code that can add correct `phase` values to commitments, based on date.
* Then make any code that loads commitments require that the user specifies phase.
* Add a …
=> DEV-573: Fix broken phase lookup for Shared Print reporting purposes

bin/cluster_validator.rb, spec/cluster_validator_spec.rb, spec/fixtures/single_cluster_invalid.json, spec/fixtures/single_cluster_valid.json
What is it? A script to identify the clusters in the Print Holdings MongoDB that are invalid. Clusters are the main organizing unit in this database. I would like to run this regularly, perhaps together with the db backup.
Why is it? An invalid cluster doesn't let you save any information on it, until you make it valid. We currently don't have good insight into this, and that could become a problem. It may in fact already be a problem and we just don't know. I'm also going to be doing stuff to the schema, which is one of the ways you can end up with invalid clusters, so that's why now.
How big is it? The diff size may look big, but when you break it down it's:
* 1 file of code: `bin/cluster_validator.rb`
* 1 file of tests: `spec/cluster_validator_spec.rb`
* 2 fixture files: …
=> A script to identify invalid clusters in Print Holdings MongoDB

lib/shared_print/phase_updater.rb, lib/shared_print/phases.rb, spec/shared_print/phase_updater_spec.rb
This is yet another PR for DEV-573.
* Added `module` block to `lib/shared_print/phase_updater.rb`
* `@date` variable is now parsed as a `DateTime` before being used in query
* Added `spec/shared_print/phase_updater_spec.rb` with one big test
The previous PR for DEV-573 (https://github.com/hathitrust/holdings-backend/pull/286) missed a few things, and did not have the desired effect. The test I'm adding here would have showed me what was missing, but I thought I could get away with not writing it. This is a teaching moment.
I'm just looking for a quick eyeball.
Turn on "hide whitespace" in the "Files changed" view, or it's going to look like the entire file `lib/shared_print/phase_updater.rb` is a diff.
Like so:
=> Fix broken fix of PhaseUpdater in Shared Print

lib/shared_print/finder.rb, spec/shared_print/finder_spec.rb
Further fix for: https://hathitrust.atlassian.net/browse/DEV-562
`SharedPrint::Finder.new(phase: [x]).commitments` should only yield commitments with `phase: x`, but the released code was missing a condition and was erroneously yielding _all commitments in a cluster_ if any one of the commitments in the cluster had `phase: x`.
This PR adds that missing condition and adds the tests to prove it's doing the right thing.
=> bugfix for DEV-562: make SharedPrint::Finder phase queries more specific

bin/setup/setup_dev.sh, bin/setup/setup_test.sh, lib/overlap/multi_part_overlap.rb, spec/overlap/multi_part_overlap_spec.rb
A partner reported that an OCLC number they hold did not appear to match any items in HathiTrust in their "ETAS overlap report".
* A HathiTrust item is considered to be a multipart monograph (MPM) if it does NOT have format SE (serial) and ANY item on the same catalog record has an enum:
https://github.com/hathitrust/holdings-backend/blob/main/lib/calculate_format.rb#L17
https://github.com/hathitrust/holdings-backend/blob/main/lib/calculate_format.rb#L43-L47
Whether a holding matches a cluster (i.e. one or more catalog records sharing a set of equivalent OCNs) or a HathiTrust item is dependent on context.
* Cost report: For MPMs, If a member reports holding an OCN but none of their reported enums match any of the enums on a HathiTrust item, they are still considered to hold it for the …
=> PHO-95: holdings with nil enum match any htitems

lib/clusterable/holding.rb, spec/clusterable/holding_spec.rb, spec/clustering/cluster_holding_spec.rb
This should address the underlying issue we were seeing with duplicate holdings not being cleaned up.
It probably would not hurt to add a test case that exercises the specific issue we were seeing -- create a cluster with a holding with some nil fields, update it with a holding with corresponding empty-string fields; ensure that they match and it doesn't end up with duplicate holdings. I will work on that next week, but wanted to get something up for a look now.
=> DEV-1124: holdings are equal if fields are equal or both empty

bin/cleanup_duplicate_holdings.rb, spec/cleanup_duplicate_holdings_spec.rb
Many clusters have duplicate holdings for reasons that have previously been discussed; see DEV-1125
This cleans up those clusters by iterating through them one by one, grouping them by update key the same way that `find_old_holdings` does (https://github.com/hathitrust/holdings-backend/blob/main/lib/clustering/cluster_holding.rb#L86-L91) and retaining the most recent in each equality group.
@mwarin Mainly I'm interested if you can think of any other tests we should be doing to make sure this does what we want.
This can be reviewed now; once approved we should wait to merge it until after #301
=> DEV-1125: duplicate holdings cleanup

lib/scrub/chunker.rb
Not sure what motivated this originally (maybe running out of space in the default temp location) but sorting in the application working directory won't work now because of the way permissions are set in the application -- in general best practice in containers for security reasons is to make the application working directory read-only by the running application.
=> Sort using the default temp location

lib/cluster.rb, lib/clusterable/holding.rb, lib/clusterable/ht_item.rb, spec/cluster_spec.rb, spec/clusterable/holding_spec.rb, spec/spec_helper.rb, spec/support/cluster_ocn_table.rb
This:
* adds the ability to instantiate `Holding`, basically the same as what we did with `HtItem`. While there may eventually be a superclass to extract here (and for other Clusterables,) I think I want to wait until at least we're handling the OCLC resolution table and the classes support validation & saving.
* adds a support context for populating the table mapping OCNs to cluster IDs
* adds the ability to find a cluster by OCN.
See also comments on individual commits.
=> DEV-1458: instantiate (but not persist) holdings & fetch associated cluster

lib/cluster.rb, lib/clusterable/ht_item.rb, spec/cluster_spec.rb, spec/clusterable/ht_item_spec.rb, spec/spec_helper.rb, spec/support/hathifiles_table.rb
* Retrieve distinct ht items with a specific set of OCNs
* Support context for adding ht items
* Change functions that return mapped rows to enumerators (to avoid unnecessarily pulling all rows into memory)
=> DEV-1459: retrieve htitems in cluster

lib/calculate_format.rb, lib/cluster.rb, lib/overlap/ht_item_overlap.rb, spec/overlap/ht_item_overlap_spec.rb
Context: https://hathitrust.atlassian.net/browse/DEV-1454
Small changes to:
* `lib/calculate_format.rb`
* `lib/cluster.rb`
* `lib/overlap/ht_item_overlap.rb`
... in order to get `lib/overlap/ht_item_overlap.rb` to run.
Remaining changes to `spec/overlap/ht_item_overlap_spec.rb` consisting either of:
* Re-organizing tests to make it cleaner which ones are enabled/disabled
* Modifying enabled tests so they work
* Disabling tests related to mpms, copying relevant tests and making them about spms
* Adding a few extra tests for good measure
Test:
```
bundle exec rspec spec/overlap/ht_item_overlap_spec.rb
bundle exec rspec
```
=> Dev 1454: ht_item_overlap for spms

lib/cluster.rb, lib/clusterable/holding.rb, lib/clustering/cluster_holding.rb, spec/clustering/cluster_holding_spec.rb, spec/integration_spec.rb, spec/loader/holding_loader_spec.rb, spec/spec_helper.rb, sql/006_holdings.sql
To be merged after #326
This adds saving holdings at a basic level but doesn't enable updating or deleting holdings.
This also enables some integration specs, including for loading holdings & creating the clustering for htitems (which will help with DEV-1486 / DEV-1487)
=> DEV-1490: enable loading holdings

sql/005_cluster_ocns.sql, sql/006_holdings.sql, sql/007_oclc_concordance.sql
* ocn uses bigint -- while the maximum real OCN fits comfortably in 32 bits, it's possible we'll have other non-OCN numbers come through, and validation practices differ across different things (hathifiles, holdings, etc)
* index ocn and organization for holdings
=> DEV-1449: schema updates for holdings/hathifile loading

docker-compose.yml
This ensures data for development persists across restarts of the container.
=> Use a persistent volume for mariadb

lib/calculate_format.rb, spec/calculate_format_spec.rb
Ensure that regardless of whether we get a blank or nil n_enum, CalculateFormat says the item is not a multi-part monograph.
=> DEV-1531: verify blank n_enum isn't an mpm

lib/frequency_table.rb, spec/frequency_table_spec.rb
- We base `+` on a new public method `append!` which does the heavy lifting.
- We discussed a number of possible optimizations, including copying parts of the addend's data structure
- Unfortunately this approach runs the risk of clone/dup copying by reference and resulting in two FTs sharing data.
- Added an `each` method so large tables need not be cloned with `to_h`
- If it turns out we don't need to be so rigorous about protecting the internals of this class, we can just make an accessor to `@table`
- Our implementation of `to_h` (`.clone.freeze`) is flawed in that the return is not a deep copy anyway.
=> DEV-1533 FrequencyTable: implement `+` method

lib/frequency_table.rb, lib/reports/cost_report.rb, spec/frequency_table_spec.rb, spec/reports/cost_report_spec.rb
- Opted to use JSON as the serialization format rather than the pre-existing custom jobby.
- As a result, all keys are symbolized including the bucket name
- E.g., `{1 => 1}` at a leaf node becomes `{:"1" => 1}`
- One-line change in `lib/frequency_table.rb` with the needed conversion to symbol.
- Further work to try to hide the details of the underlying Hash implementation.
- Remove `to_h` method and replace with `fetch` taking keywords.
- Remove default_proc in the underlying hash. Maintaining it while implementing `+` and deserialization became painful and confusing.
- Related to the above, further work to make sure `FrequencyTable` is operating on a copy of data from outside and not subject to inadvertent data sharing.
- That said, the data returned by `#fetch` is not a copy. Futz with …
=> DEV-1534 FrequencyTable: implement 'deserialize' method

config/initializers/sidekiq.rb, lib/clusterable/ocn_resolution.rb, lib/clustering/cluster_ocn_resolution.rb, lib/concordance_processing.rb, lib/concordance_validation/concordance.rb, lib/concordance_validation/delta.rb, lib/loader/ocn_resolution_loader.rb, lib/ocn_concordance_diffs.rb, spec/cluster_spec.rb, spec/clusterable/ocn_resolution_spec.rb, spec/clustering/cluster_ht_item_spec.rb, spec/clustering/cluster_ocn_resolution_spec.rb, spec/clustering/reclusterer_spec.rb, spec/concordance_validation/concordance_spec.rb, spec/disabled/clustering/cluster_commitment_spec.rb, spec/disabled/shared_print/updater_spec.rb, spec/factories/ocn_resolution.rb, spec/loader/ocn_resolution_loader_spec.rb, sql/000_schema.sql
- The names we dislike least: `variant` and `canonical`
- `oclc_concordance.oclc` becomes `oclc_concordance.variant`
- `oclc_concordance.canonical` stays the same
- `OCNResolution` exposes `variant` in place of `deprecated` and `canonical` in place of `resolved`
- Everything else is a big old find and replace, so lots of very predictable name changes.
=> Dev 1516 rename oclc concordance fields

lib/clusterable/holding.rb, lib/sidekiq_jobs.rb, spec/clusterable/holding_spec.rb, spec/reports/cost_report_spec.rb, sql/000_schema.sql
In order to "load all the data" we need to be able to load the legacy .tsv format.
There were a few small changes needed to the tsv-loader, presumably because the holdings table definitions have changed some since last we tried loading data this old.
Lines were rejected if they: lacked status, or lacked uuid, or had an outdated mono_multi_serial value. Luckily the correct or dummy value is easy to figure out. 
(I noticed that there are currently no uniqueness constraints on the `holdings` table. I think we need to figure that out, so that one cannot accidentally load the same holdings file over and over again and grow the holdings table each time. However, I don't think it is necessary to figure that out right now.)
=> DEV-1526: fixes to get the old style HT003.*.tsv holdings files to load

lib/frequency_table.rb, lib/reports/cost_report.rb, spec/frequency_table_spec.rb, spec/reports/cost_report_spec.rb
- Add FrequencyTable#frequencies method.
- Remove FrequencyTable#fetch method altogether.
- Add `FrequencyTable#keys` to replace the existing `.fetch.keys` trope.
- New `Frequency` class returned by `#frequencies`.
- Use updated classes and methods in Cost Report specs, breaking out commonly used frequency data into `let`s for direct comparison.
=> DEV-1562 continued extraction of classes in frequencytable

lib/cost_report_workflow.rb, lib/phctl.rb, lib/reports/cost_report.rb, lib/sidekiq_jobs.rb, spec/cost_report_workflow_spec.rb, spec/integration_spec.rb, spec/phctl_spec.rb, spec/spec_helper.rb, spec/support/mock_solr_response.rb
Just a quick change to add the ability to invoke the workflow via phctl.
I'm not sure `costreport-workflow` is the right name here, and there's potential confusion for this vs. `phctl report costreport`. I'm also not sure whether we want to continue to retain the ability for `CostReport` to build a frequency table itself vs. needing to take one -- I don't know that we need to fix it now, but it may be related insofar as what needs to be exposed via phctl.
=> DEV-1569: invoke cost report workflow via phctl

lib/scrub/max_ocn.rb, spec/scrub/max_ocn_spec.rb
Quick fixes for a very minor annoyance with tests that were slower than they needed to be.
* use Faraday instead of open-uri
* use FileUtils.touch instead of sleeping in max_ocn_spec
=> Quick fixes for max ocn

lib/clusterable/holding.rb, spec/scrub/scrub_runner_spec.rb, spec/spec_helper.rb
- Add `Clusterable::Holding.count` method to take the place of moribund spec helper `cluster_count`
- Add comment with future work breadcrumb in spec helper `cluster_count`
=> DEV-1613 enable & fix skipped tests in spec/scrub_runner

lib/phctl.rb, lib/sidekiq_jobs.rb, spec/clusterable/ht_item_spec.rb, spec/factories/ht_item.rb, spec/integration_spec.rb, spec/overlap/cluster_overlap_spec.rb, spec/phctl_spec.rb
Another holdings cleanup thing that we no longer need.
Not very connected, so deleting a couple of blocks of code should do it.
Fixed an unrelated brittle test in `spec/overlap/cluster_overlap_spec.rb` while I was doing it
=> DEV-1616: remove phctl "cleanup holdings"

lib/loader/holding_loader.rb, lib/scrub/scrub_runner.rb, spec/factories/loaded_file.rb, spec/loader/loaded_file_spec.rb, spec/scrub/scrub_runner_spec.rb
- Enable tests for `Loader::LoadedFile`
- TODO make this a standalone class rather than Sequel model?
- Write holdings_loaded_files entry in the loader cleanup phase
- Add `holdings_loaded_files` checks to scrub runner spec
=> DEV-1614 consider tracking holdings files via `Loader::LoadedFile`

Gemfile, Gemfile.lock, bin/api_config.ru, docker-compose.yml, lib/api/holdings_api.rb, spec/api/holdings_api_spec.rb
See https://hathitrust.atlassian.net/browse/DEV-1590
In a rare move away from "using the database as API", here's a Sinatra API that can be used to answer holdings questions (such as "how many holdings matching the volume `ht_id:foo` has `organization:bar` reported?")
Querying `v1/item_access?ht_id=foo&organization=bar` should return:
```ruby
{                                      
"copy_count" => cluster.copy_counts[organization],
"format" => cluster.format,                       
"n_enum" => ht_item.n_enum,                       
"ocns" => ht_item.ocns.sort                       
}.to_json                                  
```
It should return a `#404` if any of the arguments are missing, if the route is wrong, or if the `ht_id` does not match a `ht_item`.
`copy_count` defaults to 0, …
=> DEV-1590: API for ETAS access queries

config/environments/test.yml, lib/scrub/autoscrub.rb, lib/scrub/record_counter.rb, lib/scrub/scrub_runner.rb, spec/fixtures/umich_mon_full_20220101_ocndiff1.tsv, spec/fixtures/umich_mon_full_20220102_ocndiff2.tsv, spec/scrub/record_counter_spec.rb
`Scrub::RecordCounter` is the class that performs the line-count check between new scrubbed files and old scrubbed files (that have the same `organization` & `mono_multi_serial`) before they are loaded, in order to alert & abort in cases where the absolute change is greater than 5% (or whatever `Settings.scrub_line_count_diff_max` is set to).
This PR adds the ability to compare number of _distinct ocns_ between old & new as well, since that is likely a better predictor of fee change than plain line counts.
For instance: Assume we have already loaded a file with 1000 records of umich spm holdings via `bash phctl.sh scrub ORG`. We should then get alerted & stopped when we next try to load a file with way too few (10) or way too many (100K) holdings. This is the existing functionality.
What …
=> DEV-1640: check ocn counts as part of scrub and reject file if diff is too great

Gemfile.lock, lib/scrub/member_holding_file.rb, lib/scrub/scrub_runner.rb, lib/scrub/type_check_error.rb, lib/scrub/type_checker.rb, spec/scrub/scrub_runner_spec.rb, spec/scrub/type_checker_spec.rb
DEV-1639
This PR adds a new class, `Scrub::TypeChecker`, which checks the `mono_multi_serial` (a.k.a. `item_type`) of files-about-to-be-scrubbed against the holdings already loaded by the same member, and aborts if the types-about-to-be-scrubbed are not a subset of the types already loaded.
It's plugged into `Scrub::ScrubRunner.run`, in order to catch the type mismatch as early as possible. There are no changes needed to `phctl` or sidekiq jobs.
If the `TypeChecker` aborts the `ScrubRunner`, a human will need to intervene... we don't have a good automatic solution.
=>  DEV-1639: abort `Scrub::ScrubRunner` if it detects a type mismatch

lib/api/holdings_api.rb, spec/api/holdings_api_spec.rb, spec/support/mock_solr_response.rb
This use is quite coupled to its use from catalog indexing (given that it needs a solr record) but IMO that's OK given the desire for performance in catalog indexing, especially the full reindex. That said, given the coupling that already exists to the catalog and that we already are passing around solr records in holdings, I think it makes sense to do here and doesn't introduce any _new_ coupling.
Next step is to take a look at https://github.com/hathitrust/hathitrust_catalog_indexer/blob/main/lib/ht_traject/ht_print_holdings.rb#L13 and see whether we can in fact generate this partial record format there.
=> ETT-194: get all holdings on a record given items in JSON form

lib/api/holdings_api.rb
This enables logging for general requests and suppresses backtraces (which previously were saved even in our `error` handlers)
It might still be nice to have backtraces for "unexpected" errors, but I think it isn't critical, and the error does still get logged (just not the full backtrace)
=> ETT-256: log requests to stdout; don't dump exceptions

lib/api/holdings_api.rb, spec/api/holdings_api_spec.rb
Updated `/v1/item_access` to always provide a `brlm_count` alongside `copy_count`. Does not need `constraint=brlm`. This, being one of many ways to do it, seemed like a good compromise and was deemed acceptable by @moseshll .
An unrelated change (accounting for most of the lines in the diff) was implicitly setting the API version to 1 in all the test calls.
=> ETT-193: (Holdings API) determine if an item is held by an institution and is brittle/lost/missing

lib/api/holdings_api.rb, spec/api/holdings_api_spec.rb, spec/fixtures/organizations.rb
When we query for the value in mapto_instid (here, "stanford_mapped"), we should get the holdings for stanford.
We could have some additional tests, e.g:
* we should get the copy count we expect when there are multiple institutions with the same mapto_inst_id
=> ETT-183: mapto_instid
