README.md
=> Add docs for loading files to README

bin/add_ht_items.rb, bin/add_ocn_resolutions.rb, bin/add_print_holdings.rb, bin/load_print_serials.rb, lib/holding.rb, lib/utils/waypoint.rb
Update the scripts in bin to consistently log with the Waypoint
utility class. Waypoint itself updated to make that easier,
focusing on just providing #on_batch as the primary public
interface.
=> Update scripts to provide more consistent logging

.travis.yml, README.md, bin/add_ht_items.rb, bin/add_ocn_resolutions.rb, bin/add_print_holdings.rb, bin/load_print_serials.rb, lib/tasks/build_database.rb
Dodging rake for the moment to simply run Cluster.ensure_indexes for Travis.
=> HT-2415 ensure indices on clusters

README.md
From https://hathitrust.slack.com/archives/CST8A43T2/p1599846257204300
=> Add info on how to reset data from slack

bin/compile_estimated_hscore.rb
- computes only HScore not cost
- doesn't deal with public domain fees
- lacks tests, although I'm not sure what to test besides a comparison to a full build
=> HT-2578 Compile estimated HScore for list of ocns

.dockerignore, bin/delete_ocn_resolutions.rb, lib/cluster_holding.rb, lib/file_loader.rb, lib/holding.rb, lib/ocn_resolution_loader.rb, spec/file_loader_spec.rb, spec/holding_loader_spec.rb, spec/holding_spec.rb
- script to delete OCN resolutions (for loading delta)
- handle issn field in holdings
=> HT-2366, HT-2705: cleanup for loading all data

bin/compare_clusters.rb, lib/cluster_overlap.rb, lib/compare_cluster.rb
uses rspec matchers to compare:
- list of htids in cluster
- list of reported owners for htid
- holdings details for htid
=> HT-2638: script to compare cluster for given HTID

lib/multi_part_overlap.rb, lib/single_part_overlap.rb, spec/multi_part_overlap_spec.rb, spec/single_part_overlap_spec.rb
The existing data all uses uppercase for condition codes, and we did not normalize it to lowercase prior to loading. Not sure if this is the right solution, but it is a solution.
=> HT-2638: case for conditions codes

lib/cluster.rb, lib/ht_item_overlap.rb, lib/multi_part_overlap.rb, lib/overlap.rb, lib/serial_overlap.rb, lib/single_part_overlap.rb, spec/cluster_spec.rb, spec/compile_cost_reports_spec.rb, spec/cost_report_spec.rb, spec/ht_item_overlap_spec.rb, spec/multi_part_overlap_spec.rb, spec/overlap_spec.rb, spec/serial_overlap_spec.rb, spec/single_part_overlap_spec.rb, spec/spec_helper.rb
HT-2726 & 2727 holding/item matching corner cases
* members with holdings but no matches in cluster, match items
* member holding with enum does not match item with empty enum
* items no longer treated as holdings. only billing_entity for that individual item a match
=> Ht 2726 2727

adr/0005-concurrency.md, adr/0006-batch-loading.md
First attempt at drafting architecture decision records for performance related improvements from HT-2480, HT-2491, HT-2463, HT-2591, HT-2590 (see #45)
=> HT-2752, HT-2753: Draft ADRs for performance & consistency

lib/cluster.rb, lib/cluster_ht_item.rb, lib/reclusterer.rb, spec/cluster_ht_item_spec.rb, spec/large_clusters_spec.rb
- Batching during recluster
- Optimize when to recluster when HTItems move clusters
=> Further recluster optimizations

bin/process_new_holdings.sh, lib/autoscrub.rb, lib/member_holding.rb, lib/scrub_fields.rb, spec/member_holding_spec.rb
Addressing:
* bin/process_new_holdings.sh did not recognize .gz files in data/new/
* issues with nil values in records that had fewer columns than the header
* lib/autoscrub.rb calculating the wrong batch size for .gz files
=> minor scrub/load fixes

lib/cluster.rb
Adding a single line to index the last_modified field.
=> Add index to cluster.last_modified

bin/cost_changes.sh
=> now also generates a file for the hilites tab of the cost report

routine_tasks.md
=> Ht 3063 doc routine task

bin/reports/compile_cost_reports.rb, bin/reports/compile_member_counts_report.rb, config/environments/test.yml, config/settings.yml, lib/basic_query_report.rb, lib/reports/cost_report.rb, lib/reports/member_counts_report.rb, spec/reports/compile_cost_reports_spec.rb
Trying to figure out what's triggering the 
> Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in. (16945)
error when compiling a member counts report.
=> Ht 2568 membercounts contd

lib/clustering/reclusterer.rb, spec/clustering/reclusterer_spec.rb
Commitments weren't being reclustered.
=> HT-3254: Bugfix: recluster commitments

lib/data_sources/large_clusters.rb, spec/data_sources/large_clusters_spec.rb
* WARN not ERROR
* Empty set of OCNS
=> HT-3003: missing largeclusters file bugfix

.rubocop_todo.yml, Gemfile, Gemfile.lock, lib/cluster.rb, lib/clustering/cluster_ht_item.rb, lib/clustering/cluster_ocn_resolution.rb, lib/clustering/ocn_graph.rb, lib/clustering/reclusterer.rb, spec/clustering/cluster_ht_item_spec.rb, spec/clustering/ocn_graph_spec.rb, spec/clustering/reclusterer_spec.rb
It doesn't go as far as I would like and some of the tests need work, but I wanted to get this out before break.
=> Ht 3237 ocn reclustering avoidance

bin/reports/compile_eligible_commitments_report.rb, lib/overlap/holding_commitment.rb, lib/reports/eligible_commitments.rb, spec/fixtures/organizations.rb, spec/holdings_deleter_spec.rb, spec/overlap/holding_commitment_spec.rb, spec/reports/eligible_commitments_spec.rb, spec/scrub/auto_scrub_spec.rb
Cleanup of what was in branch `HT-1944`.
=> Ht 1944 ii

lib/clustering/reclusterer.rb
Previously we were batching reclustered components, but batch_with is limited to same OCNs. It also performs multiple database hits for the same cluster. 
This finds/builds a new cluster for each subgraph, adds the relevant components to the new cluster, and saves once.
=> HT-3321:recluster components based on ocn subgraphs

spec/utils/session_keep_alive_spec.rb
I came up with a way to test SessionKeepAlive. It is not effective in preventing CursorNotFound, at least when it is caused by MongoDB waiting on the client to make the next batch request.  Setting `Cluster.max_time_ms` was also ineffective. One or both may be useful in preventing a timeout caused by a slow database query.
Reducing batch size was effective, at least in the contrived test.
All of these tests are `xit` because they are designed to cause a database timeout (10 minutes?), but are probably good documentation for a problem we are bound to run into again.
=> Test SessionKeepAlive and ways to prevent CursorNotFound

bin/phctl.rb
I had somehow missed joining the output with tabs.
=> tabular output

lib/clusterable/commitment.rb, lib/shared_print/replace_record.rb, spec/clusterable/commitment_spec.rb, spec/clustering/cluster_commitment_spec.rb
this may not be the smartest way of doing this, but it seems to work?
=> add uuid when creating a new commitment object

bin/phctl.rb, lib/loader/cluster_loader.rb, spec/fixtures/cluster_2503661.json, spec/loader/cluster_loader_spec.rb
... to make it easier to dev/test based on data copied from prod.
Includes a spec file and an entrypoint in phctl.
=> Class for loading clusters from JSON file

bin/phctl.rb, lib/loader/cluster_loader.rb, lib/reports/rare_uncommitted.rb, spec/reports/rare_uncommitted_spec.rb
A Shared Print Phase III report for getting counts of rare (i.e. held by few) & uncommitted clusters. 
https://hathitrust.atlassian.net/browse/DEV-249
=> Report of rare uncommitted clusters: Dev 249

lib/reports/rare_uncommitted.rb
=> added marker to `Reports::RareUncommitted`

lib/shared_print/deprecation_error.rb, lib/shared_print/deprecation_record.rb, lib/shared_print/deprecator.rb, spec/shared_print/deprecation_record_spec.rb, spec/shared_print/deprecator_spec.rb
was getting errors running spo-20, having to do with expecting `[]`s but getting `nil`s
=> fixes for when there is no matching cluster

lib/reports/oclc_registration.rb, lib/reports/rare_uncommitted.rb, spec/reports/oclc_registration_spec.rb, spec/reports/rare_uncommitted_spec.rb
This is the same as #213 but targeting main (development) instead of v1.0.x (production)
=> Small fixes for Dev-250 & DEV-361

Gemfile, Gemfile.lock, spec/sidekiq_jobs_spec.rb, spec/spec_helper.rb
- Enables getting a callback when a batch of jobs completes
- Uses rspec-sidekiq to test callbacks & the batching implementation
=> Add sidekiq-batch, rspec-sidekiq

lib/shared_print/update_record.rb, lib/shared_print/updater.rb, spec/shared_print/updater_spec.rb
see https://github.com/hathitrust/holdings-backend/pull/219
=> fix for DEV-454

lib/clusterable/commitment.rb, lib/shared_print/phase_3_validator.rb, lib/shared_print/update_record.rb, spec/fixtures/phase_3_commitments.tsv, spec/shared_print/phase_3_validator_spec.rb
As per https://hathitrust.atlassian.net/browse/DEV-595, Phase 3 commitments require a retention_condition value of "ACCEPTABLE" or "EXCELLENT".
=> added retention_condition field to commitments

documentation/holdings-spec.md, generate_documentation.sh
Copied text from the PDF on https://www.hathitrust.org/print_holdings, slapped some markdown on it.
=> holdings specification in markdown

lib/reports/cost_report.rb, spec/reports/cost_report_spec.rb
Items with `rights:icus` used to be counted towards the IC part of the Print Holding cost report (meaning only the members who report holding ocns matching those items are charged for them). 
This change makes them count towards the PD part (meaning all members are charged a fraction of the cost).
Most of the lines changed have to do with the getting the tests into shameless green: changing them so that they specify rights when building ht_items (otherwise a test item built with e.g. `access:deny` could be assigned `rights:ic` as likely as `rights:icus` and that's not right).
=> Dev-906: in Print Holdings cost report, make items w/ rights:icus count towards the public domain items.

.github/workflows/tests.yml, Dockerfile, Gemfile, Gemfile.lock, lib/clusterable/ht_item.rb, lib/data_sources/holdings_db.rb, lib/enum_chron.rb, lib/services.rb, spec/clusterable/ht_item_spec.rb, spec/spec_helper.rb
* add hathifile_database gem for test so we can create the schema
* test helper to map factorybot attrs to something we can put in hf
* test round-tripping
=> DEV-1456: instantiate ht item from hf table

lib/cluster.rb, spec/cluster_spec.rb, sql/005_cluster_ocns.sql
* add cluster_ocn table
* enable tests in ocn for oclc #
* test: insert data for cluster ocns & ensure Cluster can retrieve
=> DEV-1457: retrieve ocns in cluster given id

Gemfile.lock, lib/calculate_format.rb, lib/clusterable/ht_item.rb, lib/ocnless_cluster.rb, lib/reports/cost_report.rb, spec/calculate_format_spec.rb, spec/clusterable/ht_item_spec.rb, spec/ocnless_cluster_spec.rb, spec/reports/freq_spec.rb
DEV-1488-related work on OCN-less clusters
- New `OCNLessCluster` class that acts rather like a bib record.
- First crack at FrequencyTable class with freq_spec.rb tests
=> DEV-1488 ocnless clusters

lib/clusterable/holding.rb, lib/loader/file_loader.rb, lib/loader/holding_loader.rb, lib/loader/ht_item_loader.rb, lib/loader/ocn_resolution_loader.rb, spec/integration_spec.rb, spec/loader/file_loader_spec.rb, spec/loader/holding_loader_spec.rb
As we discussed; see notes on the individual commits.
=> DEV-1528/DEV-1529: Optimize holdings load

bin/visualize_frequency_table.rb
This should be adequate to generate visualizations as needed/on demand, but if we need to do something more routinely and share with members this is probably not the best starting point.
=> DEV-1570: gnuplot visualization for frequency table

lib/clusterable/ht_item.rb, lib/ocnless_cluster.rb, lib/overlap/ht_item_overlap.rb, spec/clusterable/ht_item_spec.rb, spec/ocnless_cluster_spec.rb, spec/overlap/ht_item_overlap_spec.rb
I pulled out a couple of small changes not directly related to cost report performance from https://github.com/hathitrust/holdings-backend/pull/342 so that we can get them merged independently of the churn and experiments happening on that branch.
=> Small fixes pulled out from #342

lib/reports/estimate.rb, spec/integration_spec.rb, spec/reports/estimate_spec.rb
This is likely to be somewhat sluggish since we have to do several database queries for each OCN, but gets us something for now. We can take a look at performance and decide if we'd rather query via Solr.
Depends on #357 (which @mwarin looked at but I'd like to get a quick look from @moseshll as well as since it's pretty big)
Marked as draft just because I want to merge #357 first.
=> DEV-1571: estimates

lib/reports/estimate.rb, spec/reports/estimate_spec.rb
* fix for overcounting matched OCNs
* aligned pd/ic logic with cost report
* check OCNs we've already seen rather than hashes -- should be more resilient to data changes; also avoids collisions
=> DEV-1571: improvements for estimate

lib/clusterable/holding.rb, lib/overlap/cluster_overlap.rb, lib/overlap/overlap.rb, lib/reports/etas_organization_overlap_report.rb, spec/integration_spec.rb, spec/overlap/cluster_overlap_spec.rb, spec/overlap/etas_overlap_spec.rb, spec/reports/etas_organization_overlap_report_spec.rb
Minimal changes to try to get overlap reporting working.
=> DEV-1604 - minimal implementation for ETAS overlap report

README.md, lib/clusterable/holding.rb, lib/data_sources/mariadb.rb, lib/reports/estimate.rb, lib/reports/etas_organization_overlap_report.rb, lib/services.rb
I've deployed this to kubernetes so I can better get a handle on database performance there.
In addition to adding info on the DEBUG flags to the README, I've removed some other long-outdated information there.
=> Debug logging / performance WIP

lib/scrub/pre_load_backup.rb
Adding `strategy: :filter` to the `paged_each` in `Scrub::PreLoadBackup`
=> attempting to remedy some scrub slowness

lib/api/holdings_api.rb, spec/api/holdings_api_spec.rb
Fix for https://hathitrust.atlassian.net/browse/ETT-185?focusedCommentId=384190
=> ETT-185: check for non-existing organizations in holdings api

bin/append_sheets.pl, bin/cost_changes.sh
temporary-ish changes to add comparison of latest cost report against the report used to set the most recent budget
=> ETT-344, special budget diff
